# SPDX-FileCopyrightText: The jaas Authors
# SPDX-License-Identifier: 0BSD

version = 1

[[annotations]]
path = "examples/**"
precedence = "override"
SPDX-FileCopyrightText = "The jaas Authors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = "http/**"
precedence = "override"
SPDX-FileCopyrightText = "The jaas Authors"
SPDX-License-Identifier = "0BSD"
