# SPDX-FileCopyrightText: The jaas Authors
# SPDX-License-Identifier: 0BSD

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jaas
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: jaas
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: jaas
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: {{ .Chart.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  minAvailable: {{ if lt (.Values.replicas.min | int) 2 }}0{{ else }}1{{ end }}
