# SPDX-FileCopyrightText: The jaas Authors
# SPDX-License-Identifier: 0BSD

FROM docker.io/library/golang:latest

RUN apt-get update && apt-get install -y git
RUN go install honnef.co/go/tools/cmd/staticcheck@latest
