# SPDX-FileCopyrightText: The jaas Authors
# SPDX-License-Identifier: 0BSD

name: Verify Commits
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v5
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - id: lint
        name: Lint Go Code
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - id: tests
        name: Run Tests
        run: go test -v -cover ./...
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: container_image
        name: Build Image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            docker.io/metio/jaas:${{ github.sha }}
